### ISSUE TITLE
Helmfile Fails to Lint if version missing in charts.yaml

### ISSUE THREAD

**Issue by darkn3rd** [paulczar/helmfile-starter-kit#1]
If `version` is missing for any entry in chart, `helmfile lint` will fail.

```yaml
charts:
  azuregateway:
    enabled: true
    repository:
      name: minio
      url: https://helm.min.io/
    name: minio
    namespace: minio
    chart: minio/minio
    values:
      - ./envs/aks/tf.minio_config.yaml
```

## Actual Results

```
Error: chart "minio" matching <no value> not found in minio index. (try 'helm repo update'): improper constraint: <no value>
```

## Expected Results

`version` key would be optional.
