### ISSUE TITLE
helmfile lint fails if values omitted in charts.yaml

### ISSUE THREAD

**Issue by darkn3rd** [paulczar/helmfile-starter-kit#2]
When `values` is omitted, `helmfile lint` will yield an error.

```yaml
charts:
  dgraph:
    name: dgraph
    enabled: true
    namespace: default
    chart: /path/to/charts/charts/dgraph
    version: 0.0.11
```

## Actual Result

```
in ./helmfile.yaml: error during helmfile.yaml.part.0 parsing: template: stringTemplate:34:14: executing "stringTemplate" at <.values>: map has no entry for key "values"
```

## Expected Result

I expected that values would be optional and would not cause an error.  Use cases can include just using set values or the defaults.
